version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  dbdata: